### PR TITLE
Add to Bower

### PR DESCRIPTION
**Pull request by synapticism**
Would you consider making this available via Bower? I have prepared the required `bower.json` and cleaned up the docs a bit. After that all you have to do is accept the PR and register the package with Bower like so:
http://bower.io/docs/creating-packages/#register

At that point all you'd have to do is bump the version and make a release. (Bower relies on git tags to know what to retrieve.)

### CODE REVIEW

**Comment by Rush** [comment]
Thanks a lot! Just one question, what would be the use case? I am not a big user of bower but as I understand it's only for client-side assets, so does it mean that bower would only have pre-generated svgs and the actual generation code?

**Comment by brunowego** [comment]
+1

**Comment by synapticism** [comment]
Thanks! Yes, you're right that Bower would only pull the source files as well as the generation code... but those source files can be integrated into an asset pipeline and used to generate SVG icon sprite sheets, among other things. The same could be accomplished with npm but it's nice to have options :+1:

**Comment by synapticism** [comment]
BTW, one catch with Bower is that it'll retrieve the latest release... which won't have `bower.json` as of yet so an error will be thrown. You'll have to bump the release to complete this PR :)

In the meantime, for anyone interested in playing around, this will also work: `bower install https://github.com/encharm/Font-Awesome-SVG-PNG`.

**Comment by brunowego** [comment]
Run: bower info font-awesome-svg-png 

To list the available versions.

**Comment by synapticism** [comment]
That works because I (or someone else, but I tried it too) registered the package. However:

```
$ bower install font-awesome-svg-png
bower font-awesome-svg-png#*       not-cached git://github.com/encharm/Font-Awesome-SVG-PNG.git#*
bower font-awesome-svg-png#*          resolve git://github.com/encharm/Font-Awesome-SVG-PNG.git#*
bower font-awesome-svg-png#*         download https://github.com/encharm/Font-Awesome-SVG-PNG/archive/1.1.0.tar.gz
bower font-awesome-svg-png#*         progress received 2.6MB
bower font-awesome-svg-png#*         progress received 3.1MB
bower font-awesome-svg-png#*         progress received 3.7MB
bower font-awesome-svg-png#*         progress received 4.2MB
bower font-awesome-svg-png#*         progress received 4.6MB
bower font-awesome-svg-png#*         progress received 4.8MB
bower font-awesome-svg-png#*         progress received 5.1MB
bower font-awesome-svg-png#*          extract archive.tar.gz
bower font-awesome-svg-png#*     invalid-meta font-awesome-svg-png is missing "main" entry in bower.json
bower font-awesome-svg-png#*     invalid-meta font-awesome-svg-png is missing "ignore" entry in bower.json
bower font-awesome-svg-png#*         resolved git://github.com/encharm/Font-Awesome-SVG-PNG.git#1.1.0
bower font-awesome-svg-png#~1.1.0     install font-awesome-svg-png#1.1.0

$ ls bower_components/font-awesome-svg-png
LICENSE                 black                   package.json            white
README.md               font-awesome-svg-png.js sprites.svg
```

There's no `bower.json` in 1.1.0 therefore Bower complains about the lack of `main` and `ignore`. Solution: add and push a 1.1.1 tag.

**Comment by brunowego** [comment]
Yes, I registered minutes ago.

**Comment by synapticism** [comment]
For reference: [roll your own SVG sprite sheets with Bower and Gulp](http://synapticism.com/dev/roll-your-own-svg-sprite-sheets-with-bower-and-gulp/). That might explain a bit about the rationale for adding this project to Bower.

**Comment by Rush** [comment]
@brunowego thanks for registering, I've fallen asleep after merging the branch. :)

**Comment by Rush** [comment]
Added 1.1.2 tag, since that's the version in package.json.

**Comment by synapticism** [comment]
Checks out OK!

```
$ bower install font-awesome-svg-png -D
bower font-awesome-svg-png#*    cached git://github.com/encharm/Font-Awesome-SVG-PNG.git#1.1.2
bower font-awesome-svg-png#*  validate 1.1.2 against git://github.com/encharm/Font-Awesome-SVG-PNG.git#*
bower font-awesome-svg-png#~1.1.2          install font-awesome-svg-png#1.1.2
```

Thanks! :+1:

**Pull request merged**
