### PR TITLE
Upgrade font-awesome dep to 4.5.0 and regenerate black & white icons.

### PR DESCRIPTION
**Pull request by mareksuscak**

### CODE REVIEW

**Comment by mareksuscak** [comment]
Hmm not that I'm looking at the diff it seems that PNG files are empty. Might be the result of `--optipng` step?

**Comment by Rush** [comment]
Looks good. Sorry for taking the time to merge it.

**Comment by megawebmaster** [comment]
After merging this PR car image is broken:
https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/svg/car.svg
https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/png/128/car.png

Any reason why is that?

**Comment by mareksuscak** [comment]
@megawebmaster AFAIK this was broken even before we merged this PR - take a look at that file before the commit has been merged [here](https://github.com/encharm/Font-Awesome-SVG-PNG/blob/31dd85aef85aed8cfbe8c8d4423ca9a262a23620/black/png/128/car.png). I noticed it while working on this update but frankly I didn't have time to take a look at that issue. There are more icons that are out of borders.

**Comment by megawebmaster** [comment]
@mareksuscak - thanks, fortunately version 1.1.2 still works properly (at least for icons I'm using), so I'll keep using it.

**Comment by mareksuscak** [comment]
@megawebmaster :+1: 

@Rush Maybe the font awesome icons have been changed since it worked correctly back then and now it just doesn't. Do you think we can do something about it? I'd be happy to help but don't have time to spare in the upcoming weeks.

**Pull request merged**
