### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by dominykas**
Progress for #26.

Will add more details/commits later.

Changes:
1. Extracted `getFontData` and `getIconList` to read data from `font-awesome` npm package
2. Icons are now generated from the icon list, not from font data, i.e. the final output now contains [duplicated] aliased icons
3. Cleaned up unused packages
4. Extracted `getGlyphs`
5. Extracted and exported `require("font-awesome-svg-png").generate( options )`
6. Extracted `getIconSvg`
7. Extracted `generateIcon` and `generateSprite` into separate modules
8. Added `--dest` param for output folder

### CODE REVIEW

**Comment by Rush** [comment]
Ok I see the idea now, nice work!

**Comment by Rush** [comment]
It seems there is some bug:
`./font-awesome-svg-png.js --color black,white`

```
Generating icon align-justify for colors white
Generating icon align-justify for colors black
Generating icon align-center for colors white
Generating icon align-center for colors black
Generating icon adn for colors white
Generating icon adn for colors black
Generating icon adjust for colors white
All done!
```
And it seems it finishes prematurely. `adjust` is generated only for color white.

**Comment by dominykas** [comment]
Yeah, I noticed that it does that - but the black one is at the very top and it does get updated :)

I'm not sure where exactly do the things get out of order... probably somewhere in `flatten`... Will have a look tomorrow.

**Comment by dominykas** [comment]
OK, it's actually Bluebirds `map` that makes things go out of order. I added an update to log all items done - note how they run out of order, but once complete - the list is back in order again. I for one think that's nice and forces you to think in an async fashion, where you do NOT know in what order the results will arrive - I personally do the same when unit testing as well (i.e. run tests in random order).

```
dominykas@patti ~/devel/libs/Font-Awesome-SVG-PNG $ node ./font-awesome-svg-png.js --sprite --color white,black,red --icons car,adjust
Generating white adjust
Generating red car
Generating black car
Generating white car
Generating red adjust
Generating black adjust
Done white adjust, black adjust, red adjust, white car, black car, red car
All done!
```

**Comment by Rush** [comment]
Great job

**Pull request merged**
